Flowpack:
  OpenSearch:
    clients:
      default:
        -
          host: localhost
          port: 9200
          scheme: 'http'
          username: ''
          password: ''
    realtimeIndexing:
      enabled: true
      client: default
    transfer:
      connectionTimeout: 60
      sslVerifyPeer: true
      sslVerifyHost: true
Neos:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          Flowpack\OpenSearch\Indexer\Object\Signal\Doctrine\EmitterAdapter:
            events:
              - postUpdate
              - postPersist
              - postRemove
            listener: Flowpack\OpenSearch\Indexer\Object\Signal\Doctrine\EmitterAdapter
